### ISSUE TITLE
Question about how to set proxy?

### ISSUE THREAD

**Issue by wtksyjpy** [jbaldwin/liblifthttp#109]
Hi Josh,

Thanks for open sourcing such cool C++17 lib!
I'd like to ask if it supports setting proxy?
If yes, how could I achieve it?
I did not see examples about this.
Thank you for answering!

Best,
Hang

**Comment by jbaldwin** [comment]
Hey @wtksyjpy, you are correct the http client proxy feature isn't available yet.

I think the equivalent features in curl would be https://curl.haxx.se/libcurl/c/CURLOPT_PROXY.html correct?  Adding support for http and https proxy should be straight forward if this is what you are looking for.

I think the request signature for adding a proxy might look like this once implemented:

`lift::Request::Proxy(ProxyType type, std::string url, uint32_t port);`

And would be called like:

`Request r(...params...); r.Proxy(ProxyType::HTTP, "localhost", 80);`

Josh

**Comment by wtksyjpy** [comment]
HI Josh,

Thanks for the quick explanation!
I will try about it.

Best,
Hang
